### ISSUE TITLE
querry im Header oder Body oder URL

### ISSUE THREAD

**Issue by bela127** [bela127/MicroServiceWebShop#11]
Querry mit get im body funktioniert nicht deswegen muss es über Header oder im url als querry Parameter definiert werden...

Was soll gemacht werden?

@Moritz du hast es soweit ich weiß im Header ?

**Comment by moritz** [comment]
Falscher Moritz, vermutlich -- ich habe keine Ahnung, was du willst :D

**Comment by bela127** [comment]
@Moritz Verrückt ;) ein fremder Moritz, ja bist wohl nicht der der gemeint war.

@MoritzGoeckel passt das oben so?

**Comment by MoritzGoeckel** [comment]
@bela127 Wie zu sehen in: https://github.com/bela127/MicroServiceWebShop/blob/master/ServiceImplementation/CategoryService/src/main/java/de/hskarlsruhe/vslab/category_service/CategoryEndpoints.java

Ich habe es mit RequestHeader gemacht.
PathVariable waere auch okay, gibt keinen besonderen Grund warum ich mich fuer RequestHeader entschieden habe. Ist in der client-Library auch so implementiert, dass es so verwendet werden kann.

Solange jeder eine funktionierende client-Library zur Verfuegung stellt, ist es mir jetzt auch nicht soooo wichtig, dass das ueberall einheitlich ist.

Beantwortet das deine Frage? Ich mach mal zu. Falls es die Frage nicht beantwortet einfach wieder oeffnen.
