### ISSUE TITLE
Ribbon

### ISSUE THREAD

**Issue by MoritzGoeckel** [bela127/MicroServiceWebShop#12]
Ich habe es jetzt ein paar Stunden versucht ribbon zum laufen zu bekommen. Ohne Erfolg. Bitte hier reinschreiben, wenn jemand es zum laufen bekommt.

**Comment by MoritzGoeckel** [comment]
Habe es hin bekommen. Ich habe einen funktionierenden minimalen Client in dem neuen Projekt unter "APIImplementation/CategoryServiceClient" angelegt. In dem Client wird auch das LoadBalancing und Discovery von Ribbon verwendet. Den solltest du verwenden Bela. Verwende nicht den Client aus dem CategoryService selbst.

(Wenn ein Service versucht sich selbst zu LoadBalancen, dann ist das ein bisschen schwierig bei nur einer Instanz. Deshalb das dedizierte Projekt nur fuer den Client.)

Ich habe den Client aus dem Service mal nicht entfernt, damit man damit eben noch Tests machen kann. Aber wie gesagt: Den nicht verwenden, sondern den aus dem APIImplementation-Ordner.

Damit laeuft mein Service und sein Client. (Er muss halt so eingebunden sein, wie gezeigt in dem Client Projekt). Kannst mal ausprobieren Bela.

Wichtig ist, dass du alles innerhalb einer SpringApplication machst und, dass der Client ueber @Autowire eingebunden wird. Sonst funktioniert das nicht und es gibt Nullpointer Exceptions.

**Comment by bela127** [comment]
Supper ! 
Cool dass du es geschafft hast

Ich schau es mir heute Abend noch an ob es bei mir läuft.
