### ISSUE TITLE
category Service

### ISSUE THREAD

**Issue by bela127** [bela127/MicroServiceWebShop#13]
In diesem isue werden alle Dinge besprochen und der momentane Status des category services festgehalten.

**Comment by bela127** [comment]
Category service ist getestet und läuft

**Comment by bela127** [comment]
Welche dependency muss ich in die maven pom einbinden um deine API verwenden zu können?

**Comment by MoritzGoeckel** [comment]
Die besonderen Dependencies sind:

<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-netflix-eureka-client</artifactId>
            <version>2.0.2.RELEASE</version>
</dependency>

<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-ribbon</artifactId>
</dependency>

und die ganzen standard Spring Sachen.

Du kannst dich an der Pom des Clients orientieren. Sicher sind aber nicht alle Dependencies die da angegeben sind noetig. Aber wenn du die alle hast, dann ist das auf jeden Fall ausreichend.

**Comment by bela127** [comment]
Ok Wenn ich dich gerade richtig verstanden habe hast du keine API geschrieben sondern einen Clienten ?

Und ich soll mir aus dem Code die Teile raus kopieren die ich benötige ?

Bin davon ausgegangen dass du eine API geschrieben hast die ich als dependency einbinden und verwenden kann...

Hab mich schon gewundert wieso du da das ganze spring Boot mit einbindest...

**Comment by MoritzGoeckel** [comment]
Ja, ich habe mir das so vorgestellt, dass du dir einfach die Client-Klasse rauskopierst. Die beinhaltet auch was du fuer ribbon brauchst. Du hast ja den einzigen Service der einen Clienten braucht und dann kannst du auch das Loadbalanced rest template (ribbon) rausziehen und fuer die anderen clienten auch verwenden.

Ich denke das ist fuer alle Seiten so am einfachsten und flexiebelsten. Habe dir ja in dem Ribbon Issue geschrieben worauf du achten musst. Ist halt wichtig, dass du den Clienten von Spring per autowired instanzieren laesst.

**Comment by bela127** [comment]
Hab deinen Service mit deinem Client erfolgreich eingebunden und getestet

Hab einen Test meines Services mittels meines API gemacht der durch meinen Service auf deinen zugreift...

Hat alles funktioniert!
Perfekt :)

Jetzt müssen nur noch die anderen genau so Laufen...

Eingebunden hab ich sie ...
Aber da arbeiten die Services mit den API wohl noch nicht ganz so gut zusammen...
