### ISSUE TITLE
category und product service versuchen auf die selbe datenbank zuzugreifen und können nicht gleichzeitig gestartet werden

### ISSUE THREAD

**Issue by bela127** [bela127/MicroServiceWebShop#14]
vermutlich ein fehler bei Peter durch copy und paste?

**Comment by MoritzGoeckel** [comment]
Du kannst versuchen die Datenbank zu aendern. In der application.properties gibt es folgende Zeile:

spring.datasource.url=jdbc:h2:file:~/database

anstatt "database" kannst du da ja categoryDatabase und productDatabase verwenden.

Sollte es ein problem sein, dass sich die Datenbank-Webinterfaces ueberschneiden, so kannst du folgende Zeile aendern:

spring.h2.console.enabled=true

anstatt true verwendest du false und dann sollte es keine Webconsole mehr geben. Das koennte auch ein problem sein. Bin aber nicht sicher, vielleicht wird das auch von Spring automatisch behandelt.

Gib Bescheid ob du das so loesen konntest

**Comment by bela127** [comment]
Alles klar ich teste es...

Leider habe ich bis jetzt Mal wieder nur von dir den Code...
Also Lob an dich ;)
