### ISSUE TITLE
ProductService

### ISSUE THREAD

**Issue by bela127** [bela127/MicroServiceWebShop#16]
get Products ist fehlerhaft implementiert
es hat nur einen string parameter...
produktsuche sollte aber nach preismax, preismin, categoryid, name und id möglich sein

**Comment by PeterKaffeeKrieger** [comment]
alles klar, wird heut umgesetzt. Sollen die Suche nach Parameter einzeln erfolgen, z.b. nur nach presmax oder nur nach preismin oder nach mehreren Parameter gleichzeitig preismin + preismax + name?

**Comment by bela127** [comment]
Es sollen alle Parameter gleichzeitig berücksichtigt werden... Es müssen aber nicht immer alle Parameter gegeben sein, also können auch einzelne oder auch alle Lehr gelassen werden...

**Comment by bela127** [comment]
Außerdem ist dein API entsprechend anzupassen...

Und der Sinn eines API ist dass ich einfach Methoden aufrufen kann von denen man sofort weiß was für Parameter sie erwarten...

Nicht einen Parameter der Json String heißt...

Da weiß man nicht wie dieser Json String aussehen soll...

Mach es so wie im User role API
Entweder ein Objekt übergeben oder einzelne Felder...

**Comment by PeterKaffeeKrieger** [comment]
Alles klar. Danke :)

**Comment by bela127** [comment]
das api vom productservice funktioniert nicht

bzw es findet den productservice nicht...
ich gehe davon aus dass du in deinem service den discovery noch nicht verwendest...

und deine api mit deinem service nicht funktioniert...

**Comment by bela127** [comment]
ich hab deinen service jetzt mal so abgeändert dass er den discovery clienten verwendet

**Comment by PeterKaffeeKrieger** [comment]
cool, Danke dir :) die Änderungen an der Suche im ProductService mache ich morgen... jetzt saß ich an dem SonarQube für morgen, damit unsere Metriken grün werden

**Comment by PeterKaffeeKrieger** [comment]
die Änderungen an der Suche im ProductService mache ich morgen... wieder :D jetzt läufts aber mit der Registrierung des ProductServices und ProductServiceClients
