### ISSUE TITLE
Category Service Client fertig

### ISSUE THREAD

**Issue by MoritzGoeckel** [bela127/MicroServiceWebShop#4]
Ich habe mir die Spezifikation noch einmal angeschaut und mit was da im JSON steht bin ich nicht einverstanden. Wo wir frueher noch Strings verwendet haben stehen nun Objekte. Das macht das ganze ziemlich kompliziert.

Ich habe den generierten Client so nicht zum laufen bekommen.

Deshalb habe ich einen Client fuer den Category Service selbst geschrieben. Haelt sich aber an die Vorgaben so wie auch der generierte Client aufgebaut war. Hat ein sehr einfaches Interface und wirft im Fall der Faelle eine APIException.

Bela: Du kannst den Client einfach aus meinem Projekt rauskopieren. Ist ziemlich klein und uebersichtlich. Hier findest du alles:

Client -> CategoryServiceClient klasse
Exception -> Entweder die aus dem generierten verwenden oder meine in der ApiException klasse (Sind gleich)
Category -> In der Category Klasse

Mehr brauchst du nicht. Wenn du dir anschauen willst wie man die Client-Klasse verwendet, dann schau in die Tests in meinem Projekt.

Hoffe das passt so :)

**Comment by bela127** [comment]
Die API Spezifikation haben wir zusammen erstellt und die hat sich nicht geändert, dass sind immer noch einfache Json "Strings" die gesendet bzw empfangen werden.
In den generieren API Klassen werden diese nur automatisch in ein Objekt gepackt und können auch einfach als Objekt gepackt werden und werden dann automatisch als Json Strings Versand...

Also ist es eigentlich einfacher da man sich die Jason Strings nicht selbst bauen muss und auch kein Datenmodell implementieren muss ... Und die Json Strings nicht selbst in die Objekte umwandeln muss...

Aber was über die http Verbindung geht ist genau das selbe... Also json

Das generierte API geht also auch automatisch mit deinem Service wenn du die Daten im abgemachten Json Format sendest :)

Hättest nix umbauen müssen...

Aber trotzdem danke für die schnelle arbeit!

Ich schau mir heute (morgen) deine API Mal an bzw verwende die andere jenachdem...
Dann sollte alles laufen :)

**Comment by MoritzGoeckel** [comment]
Die generierte wird nicht funktionieren. Verwende einfach die, welche ich in meinem Projekt habe. Kannst einfach die Klasse rauskopieren, ist nicht viel. Die funktioniert dann auch. Ich uebernehme auch Garantie :D

**Comment by bela127** [comment]
Ok mach ich...
Trotzdem komisch dass es nicht funktioniert...

Rein aus Interesse weißt du wieso es nicht geht ?

**Comment by MoritzGoeckel** [comment]
Wie gesagt: Weil das in der Spezifikation super kompliziert gemacht ist und das mein Service nicht her gibt. Da geht es wesentlich schneller, dass ich den Client selber baue.

Beispiel: In der Spezifikation steht, dass man um eine Category anzulegen man ein Category Objekt als Parameter mitgeben soll. Urspruenglich sollte das nur der Name als String sein. Zweites Beispiel: Um Kategorien abzufragen muss man laut Spezifikation ein Query Objekt als Parameter uebergeben. Urspruenglich sollte einfach ein optionaler (also vielleicht leerer) String als Parameter uebergeben werden der als Query fungiert.

Hoffe das passt so alles fuer dich. Die API in Java sollte aber sehr einfach anzuwenden sein.

**Comment by bela127** [comment]
alles klar
