### ISSUE TITLE
Category Service Tests schlagen fehl

### ISSUE THREAD

**Issue by bela127** [bela127/MicroServiceWebShop#5]
alle tests deines services schlagen bei mir fehl...
wenn ich den service manuell starte bevor die tests angestoßen werde schlagen "nur" noch 3 von 5 fehl

**Comment by bela127** [comment]
tests auskommentiert damit ich bauen kann...
keine dauerhafte lösung

**Comment by MoritzGoeckel** [comment]
Du musst den Service starten und dann kannst du die Tests in der Reihenfolge starten wie es sinn macht. Also beispielsweise erst eine Category hinzufügen und dann löschen. Ich dachte nicht, dass du die tests verwendest.

Den Service und den Client habe ich getestet. Das sollte alles gehen. Die tests sind halt eher semi automatisch.

**Comment by MoritzGoeckel** [comment]
Test laufen jetzt durch wenn man davor einen Eureka Serivce am laufen hat.
