### ISSUE TITLE
User Proxy

### ISSUE THREAD

**Issue by MirkoMa** [bela127/MicroServiceWebShop#9]
In den Folien wird ein User Proxy eingebaut, wird der bei uns durch den SanityService realisiert?

**Comment by bela127** [comment]
User Proxy ?
welcher foliensatz?

muss jetzt erst mal den Service lauffähig bekommen bzw testen
was momentan nicht möglich ist da ich nicht alle eure services bauen kann...

vermutlich kommt der proxy aber in den api service wenn ich das richtig verstanden habe...

**Comment by MirkoMa** [comment]
VSMLab-W18-4-Spring-Cloud s.18ff
Da gibt es den CompositeService für Product/Category und daneben den UserProxy
